In [3]:
!pip install nltk 
# Natural Language ToolKit

In [4]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [5]:
corpus="""
Hello Welcome,to Krish Naik's NLP Tutorials.
Please do watch the entire course! to become expert in NLP.
"""

In [6]:
## Tokenization
## paragraphs-->sentence

In [7]:
from nltk.tokenize import sent_tokenize
documents=sent_tokenize(corpus)
print(documents)

["\nHello Welcome,to Krish Naik's NLP Tutorials.", 'Please do watch the entire course!', 'to become expert in NLP.']


In [8]:
## sentences --> words
from nltk.tokenize import word_tokenize
words=word_tokenize(corpus)
print(words)

['Hello', 'Welcome', ',', 'to', 'Krish', 'Naik', "'s", 'NLP', 'Tutorials', '.', 'Please', 'do', 'watch', 'the', 'entire', 'course', '!', 'to', 'become', 'expert', 'in', 'NLP', '.']


In [9]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer=TreebankWordTokenizer()
words=tokenizer.tokenize(corpus)
print(words)

['Hello', 'Welcome', ',', 'to', 'Krish', 'Naik', "'s", 'NLP', 'Tutorials.', 'Please', 'do', 'watch', 'the', 'entire', 'course', '!', 'to', 'become', 'expert', 'in', 'NLP', '.']


***Stemming***

Stemming is the process of reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words knowm as lemma.

In [10]:
## Classification Problem
## Comments of product is a positive review or negative review
## Reviews----> eating, eat,eaten [going,gone,goes]--->go

words=["eating","eats","eaten","writing","writes","programming","programs","history","finally","finalized"]

***PorterStemmer***

In [11]:
##Porter Stemmer one of technique for stemming
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [12]:
for word in words:
  print(word,"--->",stemming.stem(word))

eating ---> eat
eats ---> eat
eaten ---> eaten
writing ---> write
writes ---> write
programming ---> program
programs ---> program
history ---> histori
finally ---> final
finalized ---> final


In [13]:
stemming.stem('congratulations') ## you can see for history and congratulations , it is not giving meaningful word (disadv of stemming , we can fix using lemmatization.)

'congratul'

***RegexpStemmer class***

NLTK has RegexpStemmer class with the help of which we can easily implement Regular Expression Stemmer algorithms. It basically takes a single regular expression and removes any prefix or suffix that matches the expression. Let us see an example

In [14]:
from nltk.stem import RegexpStemmer
reg_stemmer = RegexpStemmer('ing$|s$|e$|able$', min=4)

In [15]:
reg_stemmer.stem('eating')

'eat'

In [16]:
reg_stemmer.stem('ingeating')

'ingeat'

***Snowball Stemmer***

better than porter stemmer

In [17]:
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer('english')

In [18]:
for word in words:
  print(word,"--->",stemmer.stem(word))

eating ---> eat
eats ---> eat
eaten ---> eaten
writing ---> write
writes ---> write
programming ---> program
programs ---> program
history ---> histori
finally ---> final
finalized ---> final


In [19]:
stemming.stem('fairly'),stemming.stem('sportingly')

('fairli', 'sportingli')

In [20]:
stemmer.stem('fairly'),stemmer.stem('sportingly')

('fair', 'sport')

***Lemmatization***

***Wordnet Lemmatizer***

(technique used for lemmatization)

Lemmatization technique is like stemming. The output we will get after lemmatization is called ‘lemma’, which is a root word rather than root stem, the output of stemming. After lemmatization, we will be getting a valid word that means the same thing.

NLTK provides WordNetLemmatizer class which is a thin wrapper around the wordnet corpus. This class uses morphy() function to the WordNet CorpusReader class to find a lemma. Let us understand it with an example −

In [21]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...


In [22]:
'''
POS
Noun n
Verb v
Adjective a
Adverb r
'''
lemmatizer.lemmatize('going') ## by default going is noun

'going'

In [23]:
lemmatizer.lemmatize('going',pos='v')

'go'

In [24]:
for word in words:
  print(word,"--->",lemmatizer.lemmatize(word))

eating ---> eating
eats ---> eats
eaten ---> eaten
writing ---> writing
writes ---> writes
programming ---> programming
programs ---> program
history ---> history
finally ---> finally
finalized ---> finalized


In [25]:
for word in words:
  print(word,"--->",lemmatizer.lemmatize(word,pos='v'))

eating ---> eat
eats ---> eat
eaten ---> eat
writing ---> write
writes ---> write
programming ---> program
programs ---> program
history ---> history
finally ---> finally
finalized ---> finalize


In [26]:
lemmatizer.lemmatize('goes')

'go'

In [27]:
## stemming is faster than lemmatization
## so we use this when corpus is less , ex chatbot , Q&A, text summarization

***Stop Words***

In [28]:
## Speech Of DR APJ Abdul Kalam
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
  the world have come and invaded us, captured our lands, conquered our minds.
  From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
  the French, the Dutch, all of them came and looted us, took over what was ours.
  Yet we have not done this to any other nation. We have not conquered anyone.
  We have not grabbed their land, their culture,
  their history and tried to enforce our way of life on them.
  Why? Because we respect the freedom of others.That is why my
  first vision is that of freedom. I believe that India got its first vision of
  this in 1857, when we started the War of Independence. It is this freedom that
  we must protect and nurture and build on. If we are not free, no one will respect us.
  My second vision for India’s development. For fifty years we have been a developing nation.
  It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
  in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
  Our achievements are being globally recognised today. Yet we lack the self-confidence to
  see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
  I have a third vision. India must stand up to the world. Because I believe that unless India
  stands up to the world, no one will respect us. Only strength respects strength. We must be
  strong not only as a military power but also as an economic power. Both must go hand-in-hand.
  My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
  space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
  I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
  I see four milestones in my career"""

In [29]:
from nltk.stem import PorterStemmer

In [30]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [31]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [32]:
## it is best to make your own stopwords because In this stopwords given above contains -- not,couldn't, shouldn't , for some projects like sentimental analyisis or for some other applications this not , couldn't are imp


In [33]:
stemmer=PorterStemmer()

In [34]:
sentences=nltk.sent_tokenize(paragraph)

In [35]:
## apply stopwords and filter and then apply stemming
for i in range(len(sentences)):
  words=nltk.word_tokenize(sentences[i])
  newWords=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
  sentences[i]=' '.join(newWords)

In [36]:
print(sentences)

['i three vision india .', 'in 3000 year histori , peopl world come invad us , captur land , conquer mind .', 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .', 'yet done nation .', 'we conquer anyon .', 'we grab land , cultur , histori tri enforc way life .', 'whi ?', 'becaus respect freedom others.that first vision freedom .', 'i believ india got first vision 1857 , start war independ .', 'it freedom must protect nurtur build .', 'if free , one respect us .', 'my second vision india ’ develop .', 'for fifti year develop nation .', 'it time see develop nation .', 'we among top 5 nation world term gdp .', 'we 10 percent growth rate area .', 'our poverti level fall .', 'our achiev global recognis today .', 'yet lack self-confid see develop nation , self-reli self-assur .', 'isn ’ incorrect ?', 'i third vision .', 'india must stand world .', 'becaus i believ unless india stand world , one respect us .', 'onli strength respect stre

In [37]:
from nltk.stem import SnowballStemmer
snowballstemmer=SnowballStemmer('english')

In [38]:
## Apply Stopwords And Filter And then Apply Snowball Stemming

for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[snowballstemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)# converting all the list of words into sentences

In [39]:
print(sentences)

['three vision india .', '3000 year histori , peopl world come invad us , captur land , conquer mind .', 'alexand onward , greek , turk , mogul , portugu , british , french , dutch , came loot us , took .', 'yet done nation .', 'conquer anyon .', 'grab land , cultur , histori tri enforc way life .', 'whi ?', 'becaus respect freedom others.that first vision freedom .', 'believ india got first vision 1857 , start war independ .', 'freedom must protect nurtur build .', 'free , one respect us .', 'second vision india ’ develop .', 'fifti year develop nation .', 'time see develop nation .', 'among top 5 nation world term gdp .', '10 percent growth rate area .', 'poverti level fall .', 'achiev global recogni today .', 'yet lack self-confid see develop nation , self-r self-assur .', '’ incorrect ?', 'third vision .', 'india must stand world .', 'becaus believ unless india stand world , one respect us .', 'on strength respect strength .', 'must strong militari power also econom power .', 'must

In [40]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [41]:
## Apply Stopwords And Filter And then Apply Snowball Stemming

for i in range(len(sentences)):
    #sentences[i]=sentences[i].lower()
    words=nltk.word_tokenize(sentences[i])
    words=[lemmatizer.lemmatize(word.lower(),pos='v') for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)# converting all the list of words into sentences

In [42]:
sentences

['three vision india .',
 '3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'alexand onward , greek , turk , mogul , portugu , british , french , dutch , come loot us , take .',
 'yet do nation .',
 'conquer anyon .',
 'grab land , cultur , histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom others.that first vision freedom .',
 'believ india get first vision 1857 , start war independ .',
 'freedom must protect nurtur build .',
 'free , one respect us .',
 'second vision india ’ develop .',
 'fifti year develop nation .',
 'time see develop nation .',
 'among top 5 nation world term gdp .',
 '10 percent growth rate area .',
 'poverti level fall .',
 'achiev global recogni today .',
 'yet lack self-confid see develop nation , self-r self-assur .',
 '’ incorrect ?',
 'third vision .',
 'india must stand world .',
 'becaus believ unless india stand world , one respect us .',
 'strength respect strength .',
 'must strong militari power also eco

***pos tagging***

In [43]:
sentences=nltk.sent_tokenize(paragraph)

In [44]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.


True

In [45]:
for i in range(len(sentences)):
  words=nltk.word_tokenize(sentences[i])
  words=[word for word in words if word not in set(stopwords.words('english'))]
  pos_tag=nltk.pos_tag(words)
  print(pos_tag)

[('I', 'PRP'), ('three', 'CD'), ('visions', 'NNS'), ('India', 'NNP'), ('.', '.')]
[('In', 'IN'), ('3000', 'CD'), ('years', 'NNS'), ('history', 'NN'), (',', ','), ('people', 'NNS'), ('world', 'NN'), ('come', 'VBP'), ('invaded', 'VBN'), ('us', 'PRP'), (',', ','), ('captured', 'VBD'), ('lands', 'NNS'), (',', ','), ('conquered', 'VBD'), ('minds', 'NNS'), ('.', '.')]
[('From', 'IN'), ('Alexander', 'NNP'), ('onwards', 'NNS'), (',', ','), ('Greeks', 'NNP'), (',', ','), ('Turks', 'NNP'), (',', ','), ('Moguls', 'NNP'), (',', ','), ('Portuguese', 'NNP'), (',', ','), ('British', 'NNP'), (',', ','), ('French', 'NNP'), (',', ','), ('Dutch', 'NNP'), (',', ','), ('came', 'VBD'), ('looted', 'JJ'), ('us', 'PRP'), (',', ','), ('took', 'VBD'), ('.', '.')]
[('Yet', 'RB'), ('done', 'VBN'), ('nation', 'NN'), ('.', '.')]
[('We', 'PRP'), ('conquered', 'VBD'), ('anyone', 'NN'), ('.', '.')]
[('We', 'PRP'), ('grabbed', 'VBD'), ('land', 'NN'), (',', ','), ('culture', 'NN'), (',', ','), ('history', 'NN'), ('tried'

***Named Entity Recognition***

In [46]:
"""
Person  Dheeraj Reddy
place or loc  India
date  september or 24 09 1989
time 4:30 pm
money 1 million dollar
organization  iNeuron Private Limited
Percent 20%, twenty percent
"""

'\nPerson  Dheeraj Reddy\nplace or loc  India\ndate  september or 24 09 1989\ntime 4:30 pm\nmoney 1 million dollar\norganization  iNeuron Private Limited\nPercent 20%, twenty percent\n'

In [47]:
sentence="The Eiffel Tower was built from 1887 to 1889 by Gustave Eiffel, whose company specialized in building metal frameworks and structures."

In [48]:
words=nltk.word_tokenize(sentence)

In [49]:
tag_elements=nltk.pos_tag(words)

In [50]:
nltk.download('maxent_ne_chunker')
nltk.download('words')


[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker.zip.
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.


True

In [52]:
# #print(nltk.ne_chunk(tag_elements))
# (S
#   The/DT
#   (ORGANIZATION Eiffel/NNP Tower/NNP)
#   was/VBD
#   built/VBN
#   from/IN
#   1887/CD
#   to/TO
#   1889/CD
#   by/IN
#   (PERSON Gustave/NNP Eiffel/NNP)
#   ,/,
#   whose/WP$
#   company/NN
#   specialized/VBD
#   in/IN
#   building/NN
#   metal/NN
#   frameworks/NNS
#   and/CC
#   structures/NNS
#   ./.)


In [55]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=["label","message"])

In [56]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [57]:
# Data cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [58]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()


In [59]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [60]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [61]:
## create the bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100)
## for binary bow binary=True


In [62]:
X=cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [63]:
## we have given 100 top feature , to find what are the features
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(91),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(95),
 'text': np.int64(77),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(39),
 'still': np.int64(73),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(8),
 'call': np.int64(5),
 'mobil': np.int64(48),
 'co': np.int64(9),
 'home': np.int64(30),
 'want': np.int64(90),
 'today': np.int64(82),
 'cash': np.int64(7),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(97),
 'right': np.int64(66),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(98),
 'make': np.int64(43),
 'way': np.int64(92),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(4

In [64]:
# 'go': np.int64(22),
# 'great': np.int64(25),
# this is not freq , it is the col no , if you have hello:(1)  then hello is the first feature (x1)

In [65]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 100))

N-grams

In [66]:
## create the bag of words and n-gram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()


In [67]:
cv.vocabulary_

{'go': np.int64(326),
 'point': np.int64(648),
 'crazi': np.int64(175),
 'avail': np.int64(45),
 'great': np.int64(344),
 'world': np.int64(976),
 'got': np.int64(341),
 'wat': np.int64(939),
 'ok': np.int64(592),
 'lar': np.int64(448),
 'joke': np.int64(429),
 'wif': np.int64(959),
 'free': np.int64(294),
 'entri': np.int64(245),
 'wkli': np.int64(971),
 'comp': np.int64(153),
 'win': np.int64(962),
 'final': np.int64(279),
 'st': np.int64(800),
 'may': np.int64(510),
 'text': np.int64(840),
 'receiv': np.int64(686),
 'question': np.int64(674),
 'std': np.int64(807),
 'txt': np.int64(887),
 'rate': np.int64(678),
 'appli': np.int64(34),
 'free entri': np.int64(296),
 'dun': np.int64(227),
 'say': np.int64(730),
 'earli': np.int64(230),
 'alreadi': np.int64(20),
 'nah': np.int64(554),
 'think': np.int64(848),
 'goe': np.int64(330),
 'usf': np.int64(914),
 'live': np.int64(476),
 'around': np.int64(37),
 'though': np.int64(851),
 'freemsg': np.int64(298),
 'hey': np.int64(381),
 'week':

***TF-IDF Practical***

In [68]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wordlemmatize=WordNetLemmatizer()


In [69]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [70]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[wordlemmatize.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [71]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(corpus).toarray()

In [73]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5572, 100))

In [74]:
## to see X
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter =dict(float=lambda x:"%.3g" % x))

In [75]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=100,ngram_range=(1,2))
X=tfidf.fit_transform(corpus).toarray()

In [77]:
tfidf.vocabulary_

{'go': np.int64(22),
 'great': np.int64(26),
 'got': np.int64(25),
 'wat': np.int64(89),
 'ok': np.int64(58),
 'free': np.int64(18),
 'win': np.int64(93),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'life': np.int64(38),
 'hey': np.int64(29),
 'week': np.int64(91),
 'back': np.int64(5),
 'like': np.int64(39),
 'still': np.int64(73),
 'send': np.int64(70),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(9),
 'call': np.int64(6),
 'mobile': np.int64(49),
 'co': np.int64(10),
 'home': np.int64(31),
 'want': np.int64(88),
 'today': np.int64(82),
 'cash': np.int64(8),
 'day': np.int64(14),
 'reply': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'take': np.int64(75),
 'time': np.int64(81),
 'message': np.int64(46),
 'com': np.int64(11),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(44),
 'way': np.int64(90),
 'dont': np.int64(16),
 'miss': np.int64(48),
 'ur': np.int64(8

In [78]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

***Word2Vec*** by google (**Gensim**)

In [79]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   -- ------------------------------------- 1.6/24.4 MB 9.2 MB/s eta 0:00:03
   ----- ---------------------------------- 3.4/24.4 MB 8.6 MB/s eta 0:00:03
   -------- ------------------------------- 5.0/24.4 MB 8.5 MB/s eta 0:00:03
   ----------- ---------------------------- 6.8/24.4 MB 8.5 MB/s eta 0:00:03
   -------------- ------------------------- 8.7/24.4 MB 8.5 MB/s eta 0:00:02
   --------------- ------------------------ 9.2/24.4 MB 7.6 MB/s eta 0:00:02
   ----------------- ---------------------- 10.7/24.4 MB 7.3 MB/s eta 0:00:02
   -------------------- ------------------- 12.6/24.4 MB 7.4 MB/s eta 0:00:02
   ----------------------- ---------------- 14.2/24.4 MB 7.5 MB/s eta 0:00:02
   -------------------------- ------------- 16.0/24.4 MB 7.6 MB/s eta 0:00:02
   ----------------------------- ---------- 18.1/24.4 MB 7.7 MB/s eta 0:00:01
   -------------------------------- ------- 19.7/24.4 MB 7.7 MB/s eta 0:00:01


In [80]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [81]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [82]:
vec_king

array([0.126, 0.0298, 0.00861, 0.14, -0.0256, -0.0361, 0.112, -0.198, 0.0513, 0.363, -0.242, -0.303, -0.178, -0.0249, -0.168, -0.17, 0.0347, 0.00522, 0.0464, 0.129, 0.137, 0.113, 0.0596, 0.137, 0.101, -0.177, -0.252, 0.0598, 0.342, -0.0311, 0.104, 0.0618, 0.125, 0.4, -0.322, 0.084, 0.0391, 0.00586, 0.0703, 0.173, 0.139, -0.231, 0.283, 0.143, 0.342, -0.0239, -0.11, 0.0332, -0.0547, 0.0153, -0.162, 0.158, -0.26, 0.0201, -0.163, 0.00136, -0.145, -0.0569, 0.043, -0.0247, 0.186, 0.447, 0.00958, 0.132, 0.0986, -0.186, -0.1, -0.134, -0.125, 0.283, 0.123, 0.0532, -0.178, 0.0859, -0.0219, 0.0205, -0.14, 0.0251, 0.139, -0.105, 0.139, 0.0889, -0.0752, -0.0214, 0.173, 0.0464, -0.266, 0.00891, 0.149, 0.0378, 0.238, -0.125, -0.218, -0.182, 0.0298, 0.0571, -0.0289, 0.0125, 0.0967, -0.231, 0.0581, 0.0669, 0.0708, -0.309, -0.215, 0.146, -0.428, -0.0094, 0.154, -0.0767, 0.289, 0.277, -0.000486, -0.137, 0.324, -0.246, -0.00304, -0.212, 0.125, 0.27, 0.204, 0.0825, -0.201, -0.16, -0.0378, -0.12, 0.115, -0.

In [83]:
vec_king.shape

(300,)

In [84]:
wv['cricket']

array([-0.367, -0.122, 0.285, 0.0815, 0.032, -0.032, 0.135, -0.273, 0.00946, -0.107, 0.248, -0.605, 0.0503, 0.299, 0.0957, 0.14, -0.0542, 0.291, 0.285, 0.151, -0.289, -0.0347, 0.0182, -0.393, 0.246, 0.252, -0.0986, 0.322, 0.449, -0.137, -0.234, 0.0413, -0.216, 0.17, 0.0256, 0.015, -0.0376, 0.00696, 0.4, 0.21, 0.118, -0.042, 0.234, 0.203, -0.187, -0.246, 0.312, -0.26, -0.107, 0.104, -0.18, 0.0571, -0.00742, -0.0559, 0.0762, -0.414, -0.365, -0.336, -0.154, -0.239, -0.373, 0.00227, -0.352, 0.0864, 0.127, 0.222, -0.0986, 0.109, 0.365, -0.0566, 0.0566, -0.109, -0.167, -0.0454, -0.2, -0.123, 0.132, -0.132, 0.103, -0.342, -0.157, 0.204, 0.0439, 0.244, -0.032, 0.32, -0.0442, 0.108, -0.0498, -0.00952, 0.246, -0.0559, 0.0408, -0.0178, -0.0295, 0.165, 0.504, -0.281, 0.0981, 0.0181, -0.184, 0.254, 0.226, 0.0164, 0.182, 0.139, 0.334, 0.14, 0.0146, -0.0289, -0.084, 0.15, 0.168, 0.229, 0.359, 0.123, -0.328, -0.156, 0.277, 0.0177, -0.146, -0.00452, -0.0447, 0.176, -0.375, 0.117, -0.14, 0.256, -0.196, 

In [85]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [86]:
wv.similarity("hockey","sports")

np.float32(0.5354152)

In [87]:
vec=wv['king']-wv['man']+wv['woman']
vec

array([0.043, -0.178, -0.129, 0.115, 0.00269, -0.102, 0.196, -0.18, 0.0195, 0.41, -0.368, -0.396, -0.157, 0.00146, -0.093, -0.116, -0.0552, -0.108, 0.0791, 0.199, 0.239, 0.0634, -0.0217, 0, 0.0472, -0.218, -0.345, 0.0637, 0.316, -0.198, 0.0859, -0.0812, -0.0371, 0.316, -0.342, -0.0469, 0.0977, 0.084, -0.0972, 0.0518, -0.05, -0.221, 0.229, 0.126, 0.249, 0.021, -0.11, 0.0581, -0.0336, 0.13, 0.0242, 0.0348, -0.26, 0.242, -0.322, 0.0145, -0.159, -0.0837, 0.165, 0.00159, 0.31, 0.316, 0.00739, 0.241, 0.0491, -0.0986, 0.0291, 0.149, -0.0483, 0.236, 0.221, 0.125, -0.139, 0.154, 0.0719, 0.13, -0.106, 0.0601, 0.315, 0.11, 0.085, 0.0771, -0.0217, 0.0612, -0.19, 0.208, -0.163, 0.114, 0.201, 0.0607, 0.128, -0.311, -0.28, -0.156, 0.0415, 0.0988, 0.17, -0.0349, 0.208, -0.099, 0.00439, -0.0728, -0.0425, -0.409, -0.276, 0.164, -0.558, -0.202, 0.212, -0.0981, 0.231, 0.276, 0.168, -0.045, 0.172, -0.377, -0.00352, -0.302, 0.174, 0.33, 0.201, 0.118, -0.138, -0.107, 0.0862, 0.106, 0.145, 0.00305, 0.0181, 0.

In [88]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [89]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [90]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [92]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[wordlemmatize.lemmatize(word) for word in review]
  review=' '.join(review)
  corpus.append(review)

In [93]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up