In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=['label','message'])

In [3]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
## BOW , TFIDF , CLASSIFICATION BY ML ALGO

***Data Cleaning & Preprocessing***

In [5]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [7]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

***Create Bag Of Words***

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
## binary BOW
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [10]:
X=cv.fit_transform(corpus).toarray()
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter =dict(float=lambda x:"%.3g" % x))

In [11]:
X # independent feature

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [12]:
## output features
y=pd.get_dummies(messages['label'])


In [13]:
y

,ham,spam
0,True,False
1,True,False
2,False,True
3,True,False
4,True,False
...,...,...
5567,False,True
5568,True,False
5569,True,False
5570,True,False


In [14]:
y=y.iloc[:,0].values

In [15]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True], shape=(5572,))

In [16]:
y=y.astype(int)

In [17]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5572,))

***Dataset Spliting***

In [18]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [19]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [20]:
y_pred=spam_detect_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,classification_report

In [22]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9820627802690582


In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93       150
           1       0.98      0.99      0.99       965

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



***By using TF-IDF***

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tfidf.fit_transform(corpus).toarray()

In [25]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [26]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [27]:
y_pred=spam_detect_model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,classification_report

In [29]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9811659192825112


In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.87      0.93       152
           1       0.98      1.00      0.99       963

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## ⚠️ Preventing Data Leakage

Initially, it may seem natural to perform **Bag of Words (BoW)** or **TF-IDF** on the entire dataset before splitting it into training and testing sets. However, this introduces **data leakage**.

### Why is this a problem?

BoW and TF-IDF learn the vocabulary and word statistics (such as document frequencies in TF-IDF) from the data they are fitted on. If they are fitted on the **entire dataset**, information from the **test set** is indirectly used during training.

As a result, the model gets access to information that would not be available in a real-world scenario, leading to overly optimistic evaluation results.

### ✅ Correct Workflow

1. **Preprocessing and Cleaning**
2. **Train-Test Split**
3. **Fit BoW/TF-IDF on the Training Data only**
4. **Transform both Training and Test Data using the fitted vectorizer**
5. **Train the Machine Learning Model**
6. **Evaluate on the Test Set**



1. Preprocessed and Cleaned

In [31]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

2. Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [33]:
X_train

['hi think match',
 'noth ok anyway give treat',
 'daddi take good care',
 'get ten billion call text help god',
 'guy browsin compulsori',
 'ask say pleas messag',
 'wait call',
 'dear u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr',
 'white fudg oreo store',
 'ok thk got u wan come wat',
 'wish u mani mani return day happi birthday vikki',
 'ball move lot spin last difficult bat',
 'know lt gt around',
 'v fan',
 'wat r u',
 'spoil bed well',
 'think need go late school night especi one class one miss last wednesday probabl fail test friday',
 'sore throat scratch talk',
 'free call pa',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'ah well confus thing',
 'good need receipt well done ye pleas tell number could ring',
 'freemsg claim ur sm messag text ok use web mobil ur mate etc join txt com p wk c box la wu remov txtx stop',
 'teach app da come colleg',
 'even friend priest call',
 'haha mayb u rite

In [34]:
X_test

['geeee miss alreadi know think fuck wait till next year togeth love kiss',
 'win urgent mobil number award prize guarante call land line claim valid hr ppm',
 'unsubscrib servic get ton sexi babe hunk straight phone go http gotbab co uk subscript',
 'yup msg tat yiju tot group mate co meet today mah askin leav earlier wat mah co mayb haf walk v far',
 'lick everi drop readi use mouth well',
 'beauti life next second hide thousand secret wish everi second wonder ur life gud n',
 'meet call later',
 'mean websit ye',
 'ok wun b angri msg u aft come home tonight',
 'alright good night',
 'xma new year eve ticket sale club day till pm thur fri sat night week sell fast',
 'call messag miss call',
 'winner special select receiv cash award speak live oper claim call pm cost p',
 'might come kerala day prepar take leav finalis dont plan travel visit need finish urgent work',
 'dad back ph',
 'goodmorn today late lt decim gt min',
 'come get b quit diff guess rite',
 'winner guarante caller pr

3. Apply BOW

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()

In [36]:
X_test=cv.transform(X_test).toarray()

In [37]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [38]:
cv.vocabulary_

{'hi': np.int64(934),
 'think': np.int64(2092),
 'match': np.int64(1256),
 'noth': np.int64(1452),
 'ok': np.int64(1475),
 'anyway': np.int64(76),
 'give': np.int64(804),
 'treat': np.int64(2169),
 'daddi': np.int64(482),
 'take': np.int64(2039),
 'good': np.int64(840),
 'care': np.int64(293),
 'get': np.int64(782),
 'ten': np.int64(2060),
 'call': np.int64(242),
 'text': np.int64(2069),
 'help': np.int64(927),
 'god': np.int64(830),
 'call text': np.int64(265),
 'guy': np.int64(891),
 'ask': np.int64(100),
 'say': np.int64(1785),
 'pleas': np.int64(1584),
 'messag': np.int64(1289),
 'wait': np.int64(2313),
 'wait call': np.int64(2314),
 'dear': np.int64(501),
 'invit': np.int64(1037),
 'final': np.int64(695),
 'attempt': np.int64(108),
 'contact': np.int64(409),
 'txt': np.int64(2193),
 'chat': np.int64(325),
 'suit': np.int64(2008),
 'land': np.int64(1101),
 'row': np.int64(1758),
 'hl': np.int64(944),
 'ldn': np.int64(1133),
 'yr': np.int64(2495),
 'attempt contact': np.int64(109),


4. Training the model

In [39]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [40]:
y_pred=spam_detect_model.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score,classification_report

5. evaluating the model

In [42]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9847533632286996


In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94       152
           1       0.99      0.99      0.99       963

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [46]:
X_train=tfidf.fit_transform(X_train).toarray()
X_test=tfidf.transform(X_test).toarray()

In [47]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [48]:
y_pred=spam_detect_model.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score,classification_report

In [50]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.97847533632287


In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.86      0.91       150
           1       0.98      1.00      0.99       965

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [52]:
!pip install gensim

In [53]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [54]:
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [55]:
len(corpus)

5572

In [56]:
messages.shape

(5572, 2)

In [57]:
words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [58]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  

In [59]:
import gensim

In [60]:
## lets train Word2vec from scratch
model=gensim.models.Word2Vec(words)

In [61]:
# to get all vocabulary
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'good',
 'want',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'tell',
 'still',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'new',
 'work',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'dear',
 'night',
 'messag',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'thank',
 'friend',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'tone',
 'care',
 'said',
 'cash',
 'im',
 'amp',
 'leav',
 'yeah',
 'realli',
 'babe',
 'find',
 'life',
 'morn',
 'sleep',
 'last',
 'keep',
 'servic',
 'year',
 'uk',
 'nokia',
 'sure',
 'would',
 'buy',
 'anyth',
 'com',
 'use',
 'contact',
 'start',

In [62]:
model.corpus_count
# vocabulary size

5564

In [63]:
model.epochs

5

In [64]:
model.wv.similar_by_word('good')

[('day', 0.9995504021644592),
 ('said', 0.9995320439338684),
 ('amp', 0.9995275139808655),
 ('feel', 0.9995059370994568),
 ('hope', 0.9994961023330688),
 ('like', 0.9994935393333435),
 ('dont', 0.9994854927062988),
 ('make', 0.9994717240333557),
 ('much', 0.9994677901268005),
 ('leav', 0.9994635581970215)]

In [65]:
model.wv['good'].shape

(100,)

In [66]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [67]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    sent = [word for word in doc if word in model.wv.index_to_key]
    if sent:
        return np.mean([model.wv[word] for word in sent], axis=0)
    else:
        # Return a zero vector if no in-vocabulary words are found
        return np.zeros(model.wv.vector_size)

In [68]:
from tqdm import tqdm

In [69]:
# apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 5564/5564 [00:01<00:00, 4444.18it/s]


In [70]:
X[0].shape

(100,)

In [71]:
len(X)

5564

In [72]:
## independent feature
X_new=np.array(X)

In [73]:
X_new.shape

(5564, 100)

In [74]:
## dependent feature
y
y.shape

(5572,)

In [75]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[[0, '', 'What you doing?how are you?'],
 [0, '', 'Where @'],
 [0, '', '645'],
 [0, '', 'Can a not?'],
 [0, '', ':) '],
 [0, '', 'What you doing?how are you?'],
 [0, '', ':( but your not here....'],
 [0, '', ':-) :-)']]

In [76]:
## you can see shape of x and y are not same because we mention there should be only a to z in regex so, it removes above 8 records
## we need to change y
y=messages[list(map(lambda x:len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values.astype(int)

In [77]:
y.shape

(5564,)

In [78]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5564,))

In [79]:
## i need to make X[0],X[1],.. as rows in dataframe
df_list = []
for i in range(0,len(X)):
  df_list.append(pd.DataFrame(X[i].reshape(1,-1)))
df = pd.concat(df_list, ignore_index=True)

In [80]:
## why we reshaped it
X[0].shape # 100 rows 1 col but we need 100 col 1 row
X[0].reshape(1,-1).shape

(1, 100)

In [81]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.126219,0.211480,0.093994,-0.077473,0.073083,-0.417712,0.056784,0.487187,-0.095477,-0.192208,...,0.368990,0.096796,0.027680,0.117425,0.423442,0.296432,0.213987,-0.212474,0.114161,-0.033700
1,-0.128258,0.207894,0.087851,-0.073921,0.067530,-0.402821,0.060209,0.465683,-0.093517,-0.182276,...,0.351229,0.094561,0.023843,0.106476,0.405507,0.288272,0.207788,-0.198678,0.114122,-0.030076
2,-0.138387,0.236864,0.101554,-0.083390,0.069801,-0.462853,0.060805,0.544962,-0.103608,-0.216436,...,0.408946,0.103610,0.028836,0.137298,0.476296,0.323311,0.231150,-0.233118,0.132838,-0.027646
3,-0.181256,0.304532,0.130211,-0.119892,0.105113,-0.590048,0.086759,0.686358,-0.129882,-0.264797,...,0.521936,0.138900,0.032486,0.159697,0.599618,0.415249,0.302874,-0.296801,0.162487,-0.053321
4,-0.120411,0.204996,0.088790,-0.076967,0.069581,-0.385731,0.053395,0.456917,-0.088963,-0.174282,...,0.347938,0.090741,0.021292,0.108367,0.401471,0.277736,0.203566,-0.194504,0.107168,-0.036853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5559,-0.165500,0.282852,0.117138,-0.100313,0.080636,-0.532433,0.065166,0.638289,-0.126813,-0.245493,...,0.475807,0.114625,0.035672,0.160720,0.554155,0.371078,0.267849,-0.272802,0.147620,-0.027788
5560,-0.171357,0.283543,0.122991,-0.097970,0.100255,-0.550254,0.084090,0.643460,-0.133405,-0.249134,...,0.486619,0.127680,0.035468,0.145296,0.555771,0.385738,0.281307,-0.280385,0.149733,-0.045251
5561,-0.033334,0.064093,0.030097,-0.018505,0.020180,-0.126018,0.016509,0.154422,-0.026903,-0.054235,...,0.107943,0.033920,0.011271,0.041366,0.133616,0.080153,0.066558,-0.069855,0.033590,-0.003451
5562,-0.142413,0.232892,0.101419,-0.087762,0.074286,-0.455886,0.061801,0.533940,-0.104702,-0.210583,...,0.403240,0.103626,0.029947,0.125935,0.466206,0.321629,0.227643,-0.230283,0.129609,-0.033074


In [82]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.126219,0.211480,0.093994,-0.077473,0.073083,-0.417712,0.056784,0.487187,-0.095477,-0.192208,...,0.368990,0.096796,0.027680,0.117425,0.423442,0.296432,0.213987,-0.212474,0.114161,-0.033700
1,-0.128258,0.207894,0.087851,-0.073921,0.067530,-0.402821,0.060209,0.465683,-0.093517,-0.182276,...,0.351229,0.094561,0.023843,0.106476,0.405507,0.288272,0.207788,-0.198678,0.114122,-0.030076
2,-0.138387,0.236864,0.101554,-0.083390,0.069801,-0.462853,0.060805,0.544962,-0.103608,-0.216436,...,0.408946,0.103610,0.028836,0.137298,0.476296,0.323311,0.231150,-0.233118,0.132838,-0.027646
3,-0.181256,0.304532,0.130211,-0.119892,0.105113,-0.590048,0.086759,0.686358,-0.129882,-0.264797,...,0.521936,0.138900,0.032486,0.159697,0.599618,0.415249,0.302874,-0.296801,0.162487,-0.053321
4,-0.120411,0.204996,0.088790,-0.076967,0.069581,-0.385731,0.053395,0.456917,-0.088963,-0.174282,...,0.347938,0.090741,0.021292,0.108367,0.401471,0.277736,0.203566,-0.194504,0.107168,-0.036853


In [83]:
## independent feature
X=df

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [85]:
X_train.shape

(4451, 100)

In [86]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [87]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [88]:
## actually above train work without any issue , because we already removed null values before (in avgword2vec)
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [89]:
y_pred=classifier.predict(X_test)

In [90]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, ..., 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], shape=(1113,))

In [91]:
from sklearn.metrics import accuracy_score,classification_report

In [92]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9658580413297394


In [93]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86       143
           1       0.97      0.99      0.98       970

    accuracy                           0.97      1113
   macro avg       0.95      0.90      0.92      1113
weighted avg       0.97      0.97      0.96      1113



***Kindle Review -- Sentimental Analysis***

In [94]:
import pandas as pd
df=pd.read_csv('kindle_review.csv')

In [95]:
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [96]:
## so many unnecessary columns i.e features
## reduce them
df=df[['reviewText','rating']]

In [97]:
df.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4


**Preprocessing and Cleaning**

In [98]:
## Preprocessing and Cleaning
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [99]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [100]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [101]:
## balanced dataset

In [102]:
# 1 means positive 0 means negative
df['rating']=df['rating'].apply(lambda x:1 if x>3 else 0)

In [103]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [104]:
df.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",0
1,Great short read. I didn't want to put it dow...,1
2,I'll start by saying this is the first of four...,0
3,Aggie is Angela Lansbury who carries pocketboo...,0
4,I did not expect this type of book to be in li...,1


In [105]:
## we are going to remove special chars,utls,html tags ,stopwords, remove any additional spaces
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from bs4 import BeautifulSoup
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [106]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\dheer\AppData\Local\Temp\ipykernel_3924\3853035056.py:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())


In [107]:
df.head()

,reviewText,rating
0,Jace Rankin may short hes nothing mess man hau...,0
1,Great short read I didnt want put I read one s...,1
2,Ill start saying first four books I wasnt expe...,0
3,Aggie Angela Lansbury carries pocketbooks inst...,0
4,I expect type book library pleased find price ...,1


In [108]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [109]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [110]:
lemmatizer=WordNetLemmatizer()

In [111]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [112]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [113]:
df.head()

,reviewText,rating
0,Jace Rankin may short he nothing mess man haul...,0
1,Great short read I didnt want put I read one s...,1
2,Ill start saying first four book I wasnt expec...,0
3,Aggie Angela Lansbury carry pocketbook instead...,0
4,I expect type book library pleased find price ...,1


In [114]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [115]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [117]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [118]:
X_train_bow.shape

(9600, 37028)

In [119]:
X_train_tfidf.shape

(9600, 37028)

In [120]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [122]:
c=confusion_matrix(y_test,y_pred_bow)
print(c)

[[901 271]
 [585 643]]


In [123]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.6433333333333333


In [124]:
confusion_matrix(y_test,y_pred_tfidf)



array([[942, 230],
       [749, 479]])

In [125]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5920833333333333


let's try to change the rating

In [126]:
import pandas as pd
df1=pd.read_csv('kindle_review.csv')
df1=df1[['reviewText','rating']]
df1.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4


In [127]:
df1['rating']=df1['rating'].apply(lambda x:0 if x<3 else 1)
df1['rating'].value_counts()


rating
1    8000
0    4000
Name: count, dtype: int64

In [128]:
## Removing special characters
df1['reviewText']=df1['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df1['reviewText']=df1['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df1['reviewText']=df1['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df1['reviewText']=df1['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df1['reviewText']=df1['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\dheer\AppData\Local\Temp\ipykernel_3924\1603215674.py:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df1['reviewText']=df1['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())


In [129]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])
df1['reviewText']=df1['reviewText'].apply(lambda x:lemmatize_words(x))

In [130]:
df1.head()

,reviewText,rating
0,Jace Rankin may short he nothing mess man haul...,1
1,Great short read I didnt want put I read one s...,1
2,Ill start saying first four book I wasnt expec...,1
3,Aggie Angela Lansbury carry pocketbook instead...,1
4,I expect type book library pleased find price ...,1


In [131]:
df1.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [132]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df1['reviewText'],df1['rating'],test_size=0.20)



In [133]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [134]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [135]:
c=confusion_matrix(y_test,y_pred_bow)
print(c)

[[462 340]
 [942 656]]


In [136]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.4658333333333333


In [137]:
confusion_matrix(y_test,y_pred_tfidf)


array([[459, 343],
       [938, 660]])

In [138]:
confusion_matrix(y_test,y_pred_tfidf)


array([[459, 343],
       [938, 660]])