In [3]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/65/66/53f31807a48a750f9d748da273bc3fcedd12b27ff1f3e373bfec55ef2dc0/numpy-2.5.1-cp312-cp312-win_amd64.whl.metadata
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB 640.0 kB/s eta 0:00:20
    --------------------------------------- 0.3/12.4 MB 2.8 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.4 MB 6.1 MB/s eta 0:00:02
   --- ------------------------------------ 1.2/12.4 MB 6.7 MB/s eta 0:00:02
   ---- ----------------------------------- 1.5/12.4 MB 7.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/12.4 MB 7.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/12.4 MB 7.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.7/12.4 MB 7.5 MB/s eta 0:00:02
   --------- -------------------------


[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
print("Numpy Imported Successfully")

Numpy Imported Successfully


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers.

Most NumPy arrays have some restrictions. For instance:

    All elements of the array must be of the same type of data.

    Once created, the total size of the array can’t change.

    The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

### Performance and Speed

- Enables **vectorized operations**, allowing computations on entire arrays without explicit Python loops.
- Many of its core functions are implemented in **C**, providing optimized performance.
- Uses **contiguous blocks of memory**, enabling efficient CPU caching and reducing processing overhead.

In [7]:
a=np.array([1,2,3,4,5])  # Initializing a 1D array
print(a)  # Printing the array

[1 2 3 4 5]


In [16]:
a=np.arange(15).reshape(3,5)  # Initializing a 2D array
print(a)  # Printing the array
print(type(a))  # Printing the type of the array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


**Important Attributes**

In [19]:
print(a.ndim)  # Printing the number of dimensions
print(a.shape)  # Printing the shape of the array
print(a.size)  # Printing the total number of elements in the array
print(a.dtype)  # Printing the data type of the array elements
print(a.itemsize)  # Printing the size of each element in bytes
print(a.nbytes)  # Printing the total size of the array in bytes
print(a.data)  # Printing the buffer(memory addr) containing the actual elements of the array

2
(3, 5)
15
int64
8
120


In [ ]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
print(x.itemsize)
print(x.strides)  # Output: (6, 2) # how many bytes one must move in memory to go to the next element along each dimension of the array

2
(6, 2)


In [21]:
a=np.arange(24).reshape(2,3,4)  # Initializing a 3D array
print(a)  # Printing the array

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
print(a.ndim)  # Printing the number of dimensions
print(a.shape)  # Printing the shape of the array
print(a.size)  # Printing the total number of elements in the array
print(a.dtype)  # Printing the data type of the array elements
print(a.itemsize)  # Printing the size of each element in bytes
print(a.nbytes)  # Printing the total size of the array in bytes
print(a.data)  # Printing the buffer(memory addr) containing the actual elements of the array

3
(2, 3, 4)
24
int64
8
192


In [23]:
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

In [28]:
arr_zeros=np.zeros((2,5))
print(arr_zeros)  # Printing the array of zeros
print(arr_zeros.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [29]:
arr_zeros=np.zeros((2,5),dtype=np.int32)
print(arr_zeros)  # Printing the array of zeros
print(arr_zeros.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]]
int32


In [49]:
np.zeros_like(arr_zeros) #zeros_like(array) # Creating an array of zeros with the same shape and type as the given array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [30]:
arr_ones=np.ones((2,5))
print(arr_ones)  # Printing the array of ones
print(arr_ones.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [53]:
np.full_like(arr_empty, 5) #full_like(array, value) # Creating an array with the same shape and type as the given array, filled with the specified value

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [55]:
np.empty_like(arr_empty) #empty_like(array) # Creating an empty array with the same shape and type as the given array

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [33]:
arr_empty=np.empty((2,5)) # Creating an empty array of shape (2,5) with random values
print(arr_empty)  # Printing the empty array

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
np.full((2,5), 7) # Creating an array of shape (2,5) filled with the value 7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [38]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34601642e-307, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 3.11525958e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306]])

In [39]:
np.arange(10,30,5)  # Creating an array with values from 10 to 30 with a step of 5

array([10, 15, 20, 25])

In [41]:
np.arange(0,3,0.33)  # Creating an array with values from 0 to 2 with a step of 0.3

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97])

problem with arange with float value is not possible to predict the no of elements.

In [42]:
## sol : linspace() function is used to create an array of evenly spaced values over a specified range. It is particularly useful when you want to generate a specific number of points between two values, including the endpoints.

In [44]:
## we specify no of elements
np.linspace(0,2,9)  # (start,end ,no of elements)  # Creating an array with 9 evenly spaced values between 0 and 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

***Basic Operations***

In [59]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a-b)
print(a+b)
print(a*b)
## arithmetic operartions on arrays are performed element-wise, meaning that the operation is applied to each corresponding pair of elements in the arrays.

[ 9 18 27 36]
[11 22 33 44]
[ 10  40  90 160]


In [61]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.dot(b))  # Performing matrix multiplication using the dot() function
print(a*b)  # Performing element-wise multiplication using the * operator

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [63]:
rg=np.random.default_rng(1)  # Creating a random number generator with a seed of 1
print(rg)  # Printing the random number generator object

Generator(PCG64)


In [ ]:
a=np.ones((2,3))  # Creating a 2D array of ones with shape (2,3)
a*=3  # Multiplying each element of array 'a' by 3 # inplace operation
print(a)  # Printing the modified array 'a'

[[3. 3. 3.]
 [3. 3. 3.]]


In [67]:
b=rg.random((2,3))  # Generating a 2D array of random numbers with shape (2,3)
print(b)  # Printing the array of random numbers

[[0.20345524 0.26231334 0.75036467]
 [0.28040876 0.48519097 0.9807372 ]]


In [70]:
print(b)
b+=a
print(b)

[[6.20345524 6.26231334 6.75036467]
 [6.28040876 6.48519097 6.9807372 ]]
[[9.20345524 9.26231334 9.75036467]
 [9.28040876 9.48519097 9.9807372 ]]


In [78]:
print(np.random.rand(2,5))
print(np.random.randint(0,10,(3,4)))  # Generating a 2D array of random integers between 0 and 10 with shape (3,4)


[[0.76193319 0.51790907 0.4610321  0.35069262 0.76971244]
 [0.03204404 0.39356755 0.00445863 0.99844573 0.40452024]]
[[8 2 9 2]
 [8 7 6 1]
 [7 7 4 0]]


In [81]:
a=np.random.randint(0,10,(3,4))  # Generating a 2D array of random integers between 0 and 10 with shape (3,4)
print(a)  # Printing the generated array

[[4 0 6 5]
 [8 1 7 0]
 [1 2 7 2]]


In [84]:
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.min(a))
print(np.max(a))

[[5.45981500e+01 1.00000000e+00 4.03428793e+02 1.48413159e+02]
 [2.98095799e+03 2.71828183e+00 1.09663316e+03 1.00000000e+00]
 [2.71828183e+00 7.38905610e+00 1.09663316e+03 7.38905610e+00]]
[[2.         0.         2.44948974 2.23606798]
 [2.82842712 1.         2.64575131 0.        ]
 [1.         1.41421356 2.64575131 1.41421356]]
[[-0.7568025   0.         -0.2794155  -0.95892427]
 [ 0.98935825  0.84147098  0.6569866   0.        ]
 [ 0.84147098  0.90929743  0.6569866   0.90929743]]
0
8


same way sum cummsum sort avg etc ..

***Indexing slicing iterating***

In [120]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])  # Creating a 3D array with shape (3,3,3)
print(a)  # Printing the 3D array 'a'
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [95]:
print(a[0,0])
print(a)
a[0,0]=[2,6,8]
print("after modification")
print(a)  # Printing the modified 3D array 'a'


[1 2 3]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
after modification
[[[ 2  6  8]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [99]:
print(a[2:])

[[[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [100]:
print(a[2:,2:])

[[[25 26 27]]]


In [101]:
print(a[2:,2:,1:])

[[[26 27]]]


In [104]:
for x in a:
    print(x)  # Printing each 2D slice of the 3D array 'a'
    print(".......")
    for y in x:
        print(y)  # Printing each 1D slice of the 2D array 'x'
        print(".......")
        for z in y:
            print(z)  # Printing each element of the 1D array 'y'

[[2 6 8]
 [4 5 6]
 [7 8 9]]
.......
[2 6 8]
.......
2
6
8
[4 5 6]
.......
4
5
6
[7 8 9]
.......
7
8
9
[[10 11 12]
 [13 14 15]
 [16 17 18]]
.......
[10 11 12]
.......
10
11
12
[13 14 15]
.......
13
14
15
[16 17 18]
.......
16
17
18
[[19 20 21]
 [22 23 24]
 [25 26 27]]
.......
[19 20 21]
.......
19
20
21
[22 23 24]
.......
22
23
24
[25 26 27]
.......
25
26
27


In [105]:
for element in a.flat:
    print(element)  # Printing each element of the 3D array 'a' in a flattened manner

2
6
8
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [121]:
b=a
print(b)
print(a.flatten())
print(a)
print(b)
print(a.ravel())
print(a)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [122]:

arr = np.array([[1, 2],
                [3, 4]])

In [123]:
r = arr.ravel()
r[0] = 100

print(r)
print(arr)

[100   2   3   4]
[[100   2]
 [  3   4]]


In [124]:
arr = np.array([[1, 2],
                [3, 4]])

f = arr.flatten()
f[0] = 100

print(f)
print(arr)

[100   2   3   4]
[[1 2]
 [3 4]]


ravel()-- memory is shared so it affects the original array
flatten()--return new array

In [126]:
a=np.random.randint(0,10,(3,4)) 
print(a)

[[8 1 0 7]
 [6 2 0 8]
 [0 6 4 6]]


In [127]:
a.shape

(3, 4)

**Reshaping the array**

In [128]:
a.reshape(2,6)

array([[8, 1, 0, 7, 6, 2],
       [0, 8, 0, 6, 4, 6]], dtype=int32)

In [130]:
a.resize(2, 6)
a

array([[8, 1, 0, 7, 6, 2],
       [0, 8, 0, 6, 4, 6]], dtype=int32)

In [131]:
a.reshape(6,-1)  # Reshaping the array 'a' to have 6 rows and automatically determine the number of columns

array([[8, 1],
       [0, 7],
       [6, 2],
       [0, 8],
       [0, 6],
       [4, 6]], dtype=int32)

Stacking together diff ways
vstack(vertical stack) hstack (horizontal stack)

In [132]:
## to generate random numbers best practices is:
rg=np.random.default_rng(1)  # Creating a random number generator with a seed of 1

In [134]:
a=np.floor(10*rg.random((3,4)))  # Generating a 2D array of random numbers between 0 and 10, and applying the floor function to round down to the nearest integer
b=np.floor(10*rg.random((3,4)))  # Generating another 2D array of random numbers between 0 and 10, and applying the floor function to round down to the nearest integer

In [135]:
print(a)
print(b)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
[[9. 7. 5. 2.]
 [1. 9. 5. 1.]
 [6. 7. 6. 9.]]


In [138]:
c=np.vstack((a, b))
print(c)
print(c.shape)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]
 [9. 7. 5. 2.]
 [1. 9. 5. 1.]
 [6. 7. 6. 9.]]
(6, 4)


In [139]:
c=np.hstack((a, b))
print(c)
print(c.shape)

[[3. 7. 3. 4. 9. 7. 5. 2.]
 [1. 4. 2. 2. 1. 9. 5. 1.]
 [7. 2. 4. 9. 6. 7. 6. 9.]]
(3, 8)


In [ ]:
c=np.column_stack((a, b))
print(c) ## same like hstack but it is for 2d array

[[3. 7. 3. 4. 9. 7. 5. 2.]
 [1. 4. 2. 2. 1. 9. 5. 1.]
 [7. 2. 4. 9. 6. 7. 6. 9.]]


In [142]:
a=np.array([4,2])
b=np.array([3,8])
np.column_stack((a, b))  # Stacking 1D arrays as columns into a 2D array

array([[4, 3],
       [2, 8]])

**Splittimg one array into several smaller ones**

In [147]:
a=np.floor(10*rg.random((2,12)))
print(a)

[[2. 0. 6. 7. 8. 2. 2. 6. 8. 9. 1. 4.]
 [8. 4. 5. 0. 6. 9. 8. 8. 6. 2. 7. 2.]]


In [145]:
np.hsplit(a,3)

[array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]]),
 array([[8., 5., 5., 7.],
        [8., 8., 8., 4.]])]

In [ ]:
np.hsplit(a,(3,4)) # Split `a` after the third and the fourth column

[array([[2., 0., 6.],
        [8., 4., 5.]]),
 array([[7.],
        [0.]]),
 array([[8.],
        [6.]]),
 array([[2., 2., 6., 8., 9., 1., 4.],
        [9., 8., 8., 6., 2., 7., 2.]])]

In [154]:
np.hsplit(a,(3,4,7,8))

[array([[2., 0., 6.],
        [8., 4., 5.]]),
 array([[7.],
        [0.]]),
 array([[8., 2., 2.],
        [6., 9., 8.]]),
 array([[6.],
        [8.]]),
 array([[8., 9., 1., 4.],
        [6., 2., 7., 2.]])]

**Copies and views**

In [155]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [156]:
b=a
print(b)
print("......")
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
......
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [159]:
b[1,0]=3

In [160]:
print(b)

[[ 0  1  2  3]
 [ 3  5  6  7]
 [ 8  9 10 11]]


In [161]:
print(a)

[[ 0  1  2  3]
 [ 3  5  6  7]
 [ 8  9 10 11]]


In [162]:
## both a and b shares same memory 

In [163]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [164]:
b=a.view()
print(b)
print("......")
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
......
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [165]:
b[1,0]=3
print(a)
print("....")
print(b)

[[ 0  1  2  3]
 [ 3  5  6  7]
 [ 8  9 10 11]]
....
[[ 0  1  2  3]
 [ 3  5  6  7]
 [ 8  9 10 11]]


In [166]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [167]:
b=a.copy()
print(b)
print("......")
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
......
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [168]:
b[1,0]=3
print(a)
print("....")
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
....
[[ 0  1  2  3]
 [ 3  5  6  7]
 [ 8  9 10 11]]


by creating a var by view just refer to the memory location  so any modification can affect original array.

by using copy new data is created i.e In new memory location the data is stored and refered there.

In [172]:
a=np.floor(100*rg.random((4,5)))
print(a)

[[81. 34. 54. 19. 99.]
 [24. 25.  7. 25. 76.]
 [69. 12. 37. 42. 66.]
 [45. 58. 83. 72. 36.]]


In [ ]:
a=np.sort(a) ## each row is sorted
print(a)

[[19. 34. 54. 81. 99.]
 [ 7. 24. 25. 25. 76.]
 [12. 37. 42. 66. 69.]
 [36. 45. 58. 72. 83.]]


In [181]:
a = np.array([[1, 2, 3, 4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])

In [182]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [183]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [184]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [185]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [187]:
print(a[a<5])
print(a[a%2==0])
print(np.nonzero(a<5)) #to print the indices of elements that are less than 5:

[1 2 3 4]
[ 2  4  6  8 10 12]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [188]:
data = np.array([1.0, 2.0])
data * 1.6 ## this is called broadcasting operation btw scalar and vector

array([1.6, 3.2])

In [190]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
print(data.max(axis=0)) ## max at each column in col1 --5 col2 -- 6
print(data.max(axis=1)) ## max at each row

[5 6]
[2 5 6]


In [191]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [192]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [193]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


To get the unique rows, index position, and occurrence count

In [194]:
unique_rows,indexes,occ_count=np.unique(a_2d,axis=0,return_counts=True,return_index=True)
print(unique_rows)
print(indexes)
print(occ_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [195]:
## Transpose matrix 
## a.T or a.transpose() if shape of a is (x,y) then a.T shape is (y,x)


In [196]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [197]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [198]:
np.flip(arr_2d,axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [199]:
np.flip(arr_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

**if you see for occurence count , indexes we don't know syntax we refer from doc generally** but without that we can do

In [203]:
help(np.unique) ## docstring of that function or module

Help on _ArrayFunctionDispatcher in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True, sorted=True)
    Find the unique elements of an array.

    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:

    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array

    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the s

In [205]:
import numpy as np

# Define the matrix
A = np.array([[4, 7], [2, 6]])

# Compute the matrix inverse
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [206]:
import numpy as np

# Define the matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


A masked array in NumPy is a special type of array that includes an additional Boolean mask, which marks certain elements as invalid or masked. This allows you to work with data that has missing or invalid values without having to modify the original data.

In [207]:
import numpy as np
import numpy.ma as ma

# Create a normal NumPy array
data = np.array([1, 2, -999, 4, 5])

# Mask invalid values (-999 treated as missing data)
masked_data = ma.masked_equal(data, -999)

print("Original Data:", data)
print("Masked Data:", masked_data)

# Perform operations while ignoring masked values
mean_value = masked_data.mean()
print("Mean (ignoring masked values):", mean_value)

Original Data: [   1    2 -999    4    5]
Masked Data: [1 2 -- 4 5]
Mean (ignoring masked values): 3.0
